# Default values for psutil.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: wiotp/oshi
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 8m
    memory: 96Mi
  requests:
    cpu: 4m
    memory: 64Mi


# WIoTP device configuration properties -- override these to connect
# Without any configuration, the defaults will result in a connection to Quickstart
identity:
  orgId: quickstart
  typeId: <undefined>
  deviceId: <undefined>
auth:
  token: <undefined>
